<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>

<body>
  <h1>
    Promise的返回值？？？
  </h1>
  <h2>

  </h2>
</body>

<script>
  // 网络请求: aaa -> 自己处理(10行)
  // 处理: aaa111 -> 自己处理(10行)
  // 处理: aaa111222 -> 自己处理


  // 1.返回new Promise 
  // new Promise((resolve, reject) => {
  //   setTimeout(() => {
  //     resolve('aaa')
  //   }, 1000)
  // }).then(res => {
  //   // 1.1.自己处理10行代码
  //   console.log(res, '----第一层的10行处理代码');
  //
  //   // 1.2.对结果进行第一次处理
  //   return new Promise((resolve, reject) => {
  //     // resolve(res + '111')
  //     reject('err')
  //   })
  // }).then(res => {
  //   console.log(res, '第二层的10行处理代码');
  //
  //   return new Promise(resolve => {
  //     resolve(res + '222')
  //   })
  // }).then(res => {
  //   console.log(res, '第三层的10行处理代码');
  // }).catch(err => {
  //   console.log(err);
  // })


  // // 2.返回Promise.resolve   【简写！！！】
  // // new Promise(resolve => resolve(结果))简写
  // new Promise((resolve, reject) => {
  //   setTimeout(() => {
  //     resolve('aaa')
  //   }, 1000)
  // }).then(res => {
  //   // 2.1.自己处理10行代码
  //   console.log(res, '----第一层的10行处理代码');

  //   // 2.2.对结果进行第一次处理
  //   return Promise.resolve(res + '----111----')
  // }).then(res => {
  //   console.log(res, '第二层的10行处理代码');

  //   return Promise.resolve(res + '222----')
  // }).then(res => {
  //   console.log(res, '第三层的10行处理代码');
  // })

  // // 3.Promise.resolve也省略掉，直接return【简写的最高地步！！！】，因为Promise返回的默认也是Promise？？？
  // new Promise((resolve, reject) => {
  //   setTimeout(() => {
  //     resolve('aaa')
  //   }, 1000)
  // }).then(res => {
  //   // 1.自己处理10行代码
  //   console.log(res, '----第一层的10行处理代码');

  //   // 2.对结果进行第一次处理
  //   return res + '111----'
  // }).then(res => {
  //   console.log(res, '第二层的10行处理代码');

  //   return res + '222----'
  // }).then(res => {
  //   console.log(res, '第三层的10行处理代码');
  // })


  // // 4.throw与catch的应用【遇到throw后直接执行catch函数中内容,reject是then】
  new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve('aaa')
    }, 1000)
  }).then(res => {
    // 4.1.自己处理10行代码
    console.log(res, '----第一层的10行处理代码');

    // 4.2.对结果进行第一次处理
    // return Promise.reject('error message')
    throw 'error message'
  }).then(res => {
    console.log(res, '第二层的10行处理代码');

    return Promise.resolve(res + '222----')
  }).then(res => {
    console.log(res, '第三层的10行处理代码');
  }).catch(err => {
    console.log(err);
  })
</script>

</html>